import './globals.scss';
import { Ubuntu } from 'next/font/google';
import Header from '@/components/header';
import Aside from '@/components/aside';
import UnitedStyle from '@/style/style_united.module.scss';
import My_Api from '@/my_api';

const ubuntu = Ubuntu({
  weight: ['300', '400', '500', '700'],
  display: 'swap',
  subsets: ['cyrillic', 'cyrillic-ext', 'latin', 'latin-ext'],
  style: ['normal'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  return (
    <html lang="ru" className={ubuntu.className}>
      <body>
        <Header />
        <Aside instituteLink={await My_Api.getCheckInstitute(true)} />
        <main className={UnitedStyle.scrollDiv}>
          <section className={UnitedStyle.page}>{children}</section>
        </main>
      </body>
    </html>
  );
}
