version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "2999:2999"
    volumes:
      - ./backend:/var/www/html
    restart: always
    links:
      - db

volumes:
  db_data: